/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('answers').del()
  await knex('answers').insert([
    { id: 1, question_id: 1, answer: '10 minutes ago', is_bad: 1, is_alibi: 0 },
    { id: 2, question_id: 1, answer: 'Last week', is_bad: 0, is_alibi: 0 },
    {
      id: 3,
      question_id: 1,
      answer: 'This morning at the gym',
      is_bad: 0,
      is_alibi: 1,
    },
    { id: 4, question_id: 1, answer: 'Last night', is_bad: 0, is_alibi: 0 },
    { id: 5, question_id: 2, answer: 'Squeaky', is_bad: 1, is_alibi: 0 },
    {
      id: 6,
      question_id: 2,
      answer: `Politicians wouldn't lick me`,
      is_bad: 0,
      is_alibi: 1,
    },
    { id: 7, question_id: 3, answer: `I'm bald??`, is_bad: 0, is_alibi: 1 },
    {
      id: 8,
      question_id: 3,
      answer: `I washed it today, got a hot date later`,
      is_bad: 1,
      is_alibi: 0,
    },
    {
      id: 9,
      question_id: 3,
      answer: 'Yesterday, weird question',
      is_bad: 0,
      is_alibi: 0,
    },
    {
      id: 10,
      question_id: 4,
      answer: `If snakes could fly would they technically be dragons?`,
      is_bad: 1,
      is_alibi: 0,
    },
    {
      id: 11,
      question_id: 4,
      answer: `We're in a bear market bro, too busy`,
      is_bad: 0,
      is_alibi: 0,
    },
    {
      id: 12,
      question_id: 4,
      answer: `I don't have think`,
      is_bad: 0,
      is_alibi: 1,
    },
    {
      id: 13,
      question_id: 5,
      answer: `Have you heard the new Drake song?`,
      is_bad: 1,
      is_alibi: 0,
    },
    {
      id: 14,
      question_id: 5,
      answer: `DON'T STOP... BELIEVEIN', HOLD ONTO THAT FEEEEEELIN'`,
      is_bad: 1,
      is_alibi: 0,
    },
    { id: 15, question_id: 6, answer: `Takeout`, is_bad: 0, is_alibi: 1 },
    {
      id: 16,
      question_id: 6,
      answer: `I'm a breatharian`,
      is_bad: 0,
      is_alibi: 1,
    },
    {
      id: 17,
      question_id: 6,
      answer: `The best bolognese you ever tasted`,
      is_bad: 1,
      is_alibi: 0,
    },
    {
      id: 18,
      question_id: 7,
      answer: `Warding off vampires`,
      is_bad: 0,
      is_alibi: 1,
    },
    {
      id: 19,
      question_id: 7,
      answer: `Yeah, need garlic bread with bolognese`,
      is_bad: 1,
      is_alibi: 0,
    },
    {
      id: 20,
      question_id: 7,
      answer: `Smelling people is strange, please stop`,
      is_bad: 0,
      is_alibi: 0,
    },
    {
      id: 21,
      question_id: 9,
      answer: 'In the sink',
      is_bad: 1,
      is_alibi: 0,
    },
    {
      id: 22,
      question_id: 9,
      answer: 'In da car, maaaan',
      is_bad: 0,
      is_alibi: 1,
    },
    {
      id: 23,
      question_id: 10,
      answer: 'Balmy 27 degrees',
      is_bad: 1,
      is_alibi: 0,
    },
    {
      id: 24,
      question_id: 10,
      answer: `I start sweating at 16 degrees`,
      is_bad: 0,
      is_alibi: 1,
    },
    {
      id: 25,
      question_id: 10,
      answer: `I wear long sleeves in summer`,
      is_bad: 0,
      is_alibi: 0,
    },
    {
      id: 26,
      question_id: 11,
      answer: `You know I love coriander`,
      is_bad: 0,
      is_alibi: 1,
    },
    {
      id: 27,
      question_id: 11,
      answer: `No... maybe...`,
      is_bad: 1,
      is_alibi: 0,
    },
    {
      id: 28,
      question_id: 12,
      answer: `My girlfriend's washing machine broke`,
      is_bad: 1,
      is_alibi: 0,
    },
    {
      id: 29,
      question_id: 12,
      answer: `My Mum washes my clothes`,
      is_bad: 0,
      is_alibi: 1,
    },
    {
      id: 30,
      question_id: 12,
      answer: `Sunshine is the best fabric softener`,
      is_bad: 0,
      is_alibi: 0,
    },
  ])
}
